'use strict';

// ADP-935 — PANO GEÇMİŞİ (Faz 1 çekirdeği): "peş peşe kopyaladıklarım kaybolmasın".
//
// Eren: "bir ekrandan 3-5 şey kopyalıyorum, farklı yerlere vereceğim — beşinciyi
// kopyalayınca ilk dördü gitmiş oluyor."
//
// ── BU DOSYA NEDEN AYRI (ve neden Electron'suz) ─────────────────────────────
// Yakalama kararının TAMAMI saf mantıktır: "içerik değişti mi", "bu içerik gizli
// mi", "bunu biz mi yazdık", "hangi öğe düşecek". Electron'a bağlı tek şey pano
// nesnesinin KENDİSİ; o da enjekte edilir. Böylece Windows dalı macOS'ta assert
// edilebilir (`has()` sonuçları sahte bir pano ile verilir) ve gizlilik kapısı
// gerçek parola kopyalamadan test edilebilir — ADP-933'ün ölçüm dersi tam olarak
// buydu: kapıyı yanlış API üstüne kurarsan test yeşil kalır, parolalar diske yazılır.
//
// ── ADP-933'TE GERÇEK ELECTRON 42.4.1 + GERÇEK NSPasteboard İLE ÖLÇÜLDÜ ─────
//  1. `clipboard.has('org.nspasteboard.ConcealedType')` → TRUE (parola yöneticisi
//     yazdığında). `availableFormats()` o işaretçiyi GÖRMEZ (yalnız ["text/plain"]
//     döner) ⇒ gizlilik kapısı `has()` üstüne kurulur, `availableFormats()` ile
//     ASLA — yoksa kapı sessizce hep açık kalır.
//  2. Electron'da `changeCount` muadili YOK ⇒ değişim algısı İÇERİK FARKI ile
//     yapılır. BEDELİ (MVP sınırı): aynı içeriği arka arkaya iki kez kopyalamak
//     ikinci kez GÖRÜNMEZ. Kalıcı çözüm native yardımcı (Faz 2).
//  3. `readImage()` `readText()`ten ~470× pahalı (1319 µs / 1.6 µs) ⇒ görüntü
//     yalnız `availableFormats()` `image/png` derse ve YALNIZ kısıtlanmış aralıkla
//     okunur; boş panoda maliyet sıfırdır.
//  4. `writeBuffer(custom)` + `write({text})` karşılıklı YIKICI ⇒ geri yazdığımız
//     içeriği `TransientType` ile İŞARETLEYEMEYİZ. Kendi yazdığımızı geçmişe geri
//     kaydetmemenin tek yolu bir İÇERİK DAMGASIdır (`markSelfWrite`) — döngü kırıcı.
//
// ── GİZLİLİK DURUŞU ─────────────────────────────────────────────────────────
// Geçmiş YALNIZ BELLEKTE yaşar: diske yazılmaz, senkron/telemetri yoktur,
// uygulama kapanınca gider. "Pano geçmişi diskte" yeni bir sır yüzeyidir ve
// MVP'de o yüzey hiç açılmaz (ADP-933 §9 R5).

const crypto = require('node:crypto');

/**
 * KAYDETME işaretçileri. Bir pano öğesi bunlardan HERHANGİ birini taşıyorsa
 * geçmişe ALINMAZ. Konvansiyon: nspasteboard.org (macOS) + Microsoft "Clipboard
 * Formats" (Windows). 1Password/Bitwarden/KeePassXC bunları koyar.
 *
 * ⚠️ Windows işaretçileri ADP-933'te ÖLÇÜLEMEDİ (ölçüm makinesi macOS 14.6).
 * Yine de listede DURUYORLAR: ölçülmemiş bir platformda kapı FAIL-SAFE tarafa
 * düşmelidir — "muhtemelen gerekmez" demek parola sızdırmaktır. Yanlış-pozitifin
 * bedeli bir öğenin geçmişe girmemesi; yanlış-negatifin bedeli parolanın girmesi.
 */
const PRIVACY_MARKERS = Object.freeze([
  // macOS — ölçüldü (ADP-933 §2.1): has() bunu GÖRÜYOR.
  'org.nspasteboard.ConcealedType',
  // macOS — anlık içerik / kullanıcı kopyalamadı (aynı konvansiyon ailesi).
  'org.nspasteboard.TransientType',
  'org.nspasteboard.AutoGeneratedType',
  // Windows — ÖLÇÜLMEDİ (yukarıdaki not).
  'ExcludeClipboardContentFromMonitorProcessing',
  'CanIncludeInClipboardHistory',
  'Clipboard Viewer Ignore',
]);

/** Değişmez varsayılanlar — hepsi ctor'dan geçersiz kılınabilir (test kolaylığı). */
const DEFAULTS = Object.freeze({
  maxItems: 50,
  /** Görüntü öğesi tavanı: PNG baytları bellekte durur, sınırsız büyüyemez. */
  maxImages: 12,
  /** Görüntülerin TOPLAM bayt tavanı (bu aşılırsa en eski görüntü düşer). */
  maxImageBytes: 48 * 1024 * 1024,
  /** Tek görüntünün bayt tavanı (dev ekran görüntüsü belleği yemesin). */
  maxSingleImageBytes: 16 * 1024 * 1024,
  /** Metin tavanı — `clipboard:write`ın CLIPBOARD_MAX'ı ile aynı (1 MB). */
  maxTextChars: 1024 * 1024,
  /** Listede gösterilen önizleme uzunluğu (tam metin renderer'a listede GEÇMEZ). */
  previewChars: 200,
  /** `readImage()` en fazla bu sıklıkta çağrılır (ölçüm #3: 470× pahalı). */
  imageProbeMs: 1200,
});

/** sha256 — içerik farkı ve döngü kırıcı damga aynı fonksiyondan türer. */
function sha256(buf) {
  return crypto.createHash('sha256').update(buf).digest('hex');
}

/**
 * Metnin tek satırlık önizlemesi: ilk DOLU satır, kırpılmış. Kart bir satır
 * gösteriyor; oraya "\n\n\n" ile başlayan bir blok gelirse kullanıcı BOŞ satır
 * görür ve öğe kaybolmuş sanır.
 */
function textPreview(text, max) {
  const firstLine = text.split(/\r?\n/).find((l) => l.trim().length > 0) || text.trim();
  const flat = firstLine.replace(/\s+/g, ' ').trim();
  return flat.length > max ? `${flat.slice(0, max)}…` : flat;
}

/**
 * ⛔ GİZLİLİK KAPISI — saf. `has` enjekte edilir (gerçek hayatta
 * `clipboard.has`), böylece Windows dalı macOS'ta test edilebilir.
 * `has` fırlatırsa (bilinmeyen tür / platform) FAIL-SAFE: "gizli say".
 */
function isConcealed(has) {
  for (const marker of PRIVACY_MARKERS) {
    let hit = false;
    try {
      hit = !!has(marker);
    } catch {
      // Sorgulayamadığımız bir işaretçi "yok" demek DEĞİLDİR.
      return true;
    }
    if (hit) return true;
  }
  return false;
}

/**
 * Pano geçmişi deposu + poll döngüsünün TEK adımı.
 *
 * @param {object} deps
 * @param {object} deps.clipboard  Electron `clipboard` (ya da test sahtesi):
 *                                 availableFormats/readText/readImage/has/writeText/writeImage
 * @param {() => number} [deps.now] Zaman kaynağı (test enjekte eder).
 * @param {(id:string) => void} [deps.onChange] Geçmiş değişti (yayın tetikleyicisi).
 * @param {(line:string) => void} [deps.log]
 */
function createClipboardHistory(deps) {
  const {
    clipboard,
    now = () => Date.now(),
    onChange = () => {},
    log = () => {},
    ...rest
  } = deps || {};
  const cfg = { ...DEFAULTS, ...rest };

  /** En YENİ başta: liste sırası ekranın sırasıdır (ayrıca sıralama yapılmaz). */
  const items = [];
  let seq = 0;
  /** En son GÖRÜLEN pano imzası — içerik farkının hafızası (ölçüm #2). */
  let lastSeenSig = null;
  /** Kendi yazdığımızın imzası — döngü kırıcı (ölçüm #4). */
  let selfSig = null;
  let lastImageProbeAt = 0;

  function publicItem(it) {
    return {
      id: it.id,
      kind: it.kind,
      at: it.at,
      preview: it.preview,
      chars: it.chars,
      width: it.width,
      height: it.height,
      bytes: it.bytes,
      // Küçük resim veri-URL'i: görüntü BAYTLARI renderer'a geçmez, yalnız
      // ~40px yüksekliğinde bir önizleme geçer (liste ucuz kalsın).
      thumb: it.thumb,
    };
  }

  /** Tavanları uygula: önce öğe sayısı, sonra görüntü sayısı/baytı. */
  function prune() {
    while (items.length > cfg.maxItems) items.pop();
    let imageCount = 0;
    let imageBytes = 0;
    for (let i = 0; i < items.length; i += 1) {
      const it = items[i];
      if (it.kind !== 'image') continue;
      imageCount += 1;
      imageBytes += it.bytes || 0;
      if (imageCount > cfg.maxImages || imageBytes > cfg.maxImageBytes) {
        // Bu ve bundan ESKİ görüntüler düşer (metin öğeleri korunur — ucuzlar).
        for (let j = items.length - 1; j >= i; j -= 1) {
          if (items[j].kind === 'image') items.splice(j, 1);
        }
        break;
      }
    }
  }

  /**
   * Yeni öğeyi başa koy. Aynı imza geçmişte BAŞKA bir yerde varsa eskisi silinir
   * ve öğe başa taşınır — "eski bir şeyi tekrar kopyaladım" hareketi kullanıcı
   * için de yukarı taşıma demektir (yoksa liste ikizlerle dolar).
   */
  function push(item) {
    const dupIndex = items.findIndex((it) => it.sig === item.sig);
    if (dupIndex >= 0) items.splice(dupIndex, 1);
    items.unshift(item);
    prune();
    onChange(item.id);
    return item.id;
  }

  /**
   * Poll'un TEK adımı. Dönüş: { status, id? }
   *   'unchanged' pano değişmedi (en sık dal — iki ucuz çağrı, ~4 µs)
   *   'captured'  yeni öğe eklendi
   *   'private'   ⛔ gizlilik işaretçisi vardı → KAYDEDİLMEDİ
   *   'self'      kendi geri-yazdığımız içerik → döngü kırıldı
   *   'too-large' tavanı aştı
   *   'empty'     panoda kullanılabilir içerik yok
   */
  function tick() {
    let formats;
    let text;
    try {
      // ÖLÇÜM #3: bu iki çağrı bedava (2.8 µs + 1.6 µs). Pahalı olan readImage
      // yalnız aşağıdaki dalda ve yalnız throttle ile çağrılır.
      formats = clipboard.availableFormats() || [];
      text = clipboard.readText() || '';
    } catch (err) {
      log(`[clip] pano okunamadı: ${err && err.message}`);
      return { status: 'empty' };
    }

    // METİN ÖNCELİKLİ (ADP-925 ile aynı kural): bir web sayfasından yapılan
    // "kopyala" çoğu zaman metinle BİRLİKTE bir görüntü de bırakır ve kullanıcının
    // beklediği metindir.
    if (text.trim()) {
      const sig = `text:${sha256(text)}`;
      if (sig === lastSeenSig) return { status: 'unchanged' };
      lastSeenSig = sig;
      if (sig === selfSig) return { status: 'self' };
      if (text.length > cfg.maxTextChars) return { status: 'too-large' };
      // ⛔ Kapı: SADECE içerik değiştiğinde sorulur (her tik değil).
      if (isConcealed((m) => clipboard.has(m))) {
        log('[clip] gizli içerik atlandı (gizlilik işaretçisi)');
        return { status: 'private' };
      }
      seq += 1;
      return {
        status: 'captured',
        id: push({
          id: `clip-${now()}-${seq}`,
          kind: 'text',
          sig,
          at: now(),
          text,
          preview: textPreview(text, cfg.previewChars),
          chars: text.length,
        }),
      };
    }

    if (formats.includes('image/png')) {
      const at = now();
      if (at - lastImageProbeAt < cfg.imageProbeMs) return { status: 'unchanged' };
      lastImageProbeAt = at;
      let png = null;
      let size = { width: 0, height: 0 };
      let thumb = null;
      try {
        const img = clipboard.readImage();
        if (!img || img.isEmpty()) return { status: 'empty' };
        png = img.toPNG();
        size = img.getSize();
        // Küçük resim SABİT yükseklikte: kart 40px'lik satır çiziyor, oraya 4K
        // ekran görüntüsünün data-URL'ini göndermek listeyi megabaytlara çıkarırdı.
        thumb = img.resize({ height: 40, quality: 'good' }).toDataURL();
      } catch (err) {
        log(`[clip] görüntü okunamadı: ${err && err.message}`);
        return { status: 'empty' };
      }
      if (!png || png.length === 0) return { status: 'empty' };
      const sig = `image:${sha256(png)}`;
      if (sig === lastSeenSig) return { status: 'unchanged' };
      lastSeenSig = sig;
      if (sig === selfSig) return { status: 'self' };
      if (png.length > cfg.maxSingleImageBytes) return { status: 'too-large' };
      if (isConcealed((m) => clipboard.has(m))) {
        log('[clip] gizli görüntü atlandı (gizlilik işaretçisi)');
        return { status: 'private' };
      }
      seq += 1;
      return {
        status: 'captured',
        id: push({
          id: `clip-${at}-${seq}`,
          kind: 'image',
          sig,
          at,
          png,
          thumb,
          width: size.width,
          height: size.height,
          bytes: png.length,
          preview: `${size.width}×${size.height}`,
        }),
      };
    }

    lastSeenSig = null;
    return { status: 'empty' };
  }

  return {
    tick,
    /** Renderer'a giden liste — TAM METİN YOK (yalnız önizleme + üst veri). */
    list: () => items.map(publicItem),
    /** Main-içi tam kayıt (teslimatta kullanılır). */
    get: (id) => items.find((it) => it.id === id) || null,
    remove(id) {
      const i = items.findIndex((it) => it.id === id);
      if (i < 0) return false;
      items.splice(i, 1);
      onChange(id);
      return true;
    },
    clear() {
      const n = items.length;
      items.length = 0;
      // Silinen içerik bir daha yakalanmasın diye imza SIFIRLANMAZ: kullanıcı
      // "temizle" dedi, aynı içerik hâlâ panoda duruyor — geri yazmak "temizle"
      // düğmesini anlamsız kılardı.
      if (n) onChange('');
      return n;
    },
    /**
     * Döngü kırıcı: bu içeriği BİZ panoya yazdık, poll onu yeni kopya sanmasın.
     * `kind` + ham içerik verilir; imza `tick()`in ürettiğiyle aynı biçimdedir.
     */
    markSelfWrite(kind, payload) {
      selfSig = `${kind}:${sha256(payload)}`;
      // `lastSeenSig`i de damgala: aksi hâlde bir sonraki tik "değişti" der,
      // `selfSig` dalına düşer ve her seferinde bir log satırı üretirdi.
      lastSeenSig = selfSig;
      return selfSig;
    },
    size: () => items.length,
  };
}

module.exports = { createClipboardHistory, isConcealed, textPreview, PRIVACY_MARKERS, DEFAULTS };
