'use strict';
/**
 * CrewPane Domain: SERVICES
 */
const path = require('node:path');

module.exports = {
  get announcements() { return require(path.join(__dirname, "announcements.cjs")); },
  get attachmentStore() { return require(path.join(__dirname, "attachmentStore.cjs")); },
  get browserCdp() { return require(path.join(__dirname, "browserCdp.js")); },
  get changelogFeed() { return require(path.join(__dirname, "changelogFeed.cjs")); },
  get clipboardHistory() { return require(path.join(__dirname, "clipboardHistory.cjs")); },
  get clipboardImageRoute() { return require(path.join(__dirname, "clipboardImageRoute.cjs")); },
  get codeIndex() { return require(path.join(__dirname, "codeIndex.cjs")); },
  get codeIndexHealth() { return require(path.join(__dirname, "codeIndexHealth.cjs")); },
  get codeIntel() { return require(path.join(__dirname, "codeIntel.cjs")); },
  get customProvider() { return require(path.join(__dirname, "customProvider.cjs")); },
  get deepLinkArgv() { return require(path.join(__dirname, "deepLinkArgv.cjs")); },
  get entityResolve() { return require(path.join(__dirname, "entityResolve.cjs")); },
  get evidencePath() { return require(path.join(__dirname, "evidencePath.cjs")); },
  get feedbackBridge() { return require(path.join(__dirname, "feedbackBridge.cjs")); },
  get inputSim() { return require(path.join(__dirname, "inputSim.cjs")); },
  get logTarget() { return require(path.join(__dirname, "logTarget.cjs")); },
  get markerSafe() { return require(path.join(__dirname, "markerSafe.cjs")); },
  get mergePolicy() { return require(path.join(__dirname, "mergePolicy.cjs")); },
  get mergeService() { return require(path.join(__dirname, "mergeService.cjs")); },
  get notifyGate() { return require(path.join(__dirname, "notifyGate.cjs")); },
  get notifyLog() { return require(path.join(__dirname, "notifyLog.cjs")); },
  get notifyPath() { return require(path.join(__dirname, "notifyPath.cjs")); },
  get pastePayload() { return require(path.join(__dirname, "pastePayload.cjs")); },
  get popoutBounds() { return require(path.join(__dirname, "popoutBounds.cjs")); },
  get reportsWatcher() { return require(path.join(__dirname, "reportsWatcher.cjs")); },
  get resultRoot() { return require(path.join(__dirname, "resultRoot.cjs")); },
  get screenCapture() { return require(path.join(__dirname, "screenCapture.cjs")); },
  get settingsMigrations() { return require(path.join(__dirname, "settingsMigrations.cjs")); },
  get tempImageStore() { return require(path.join(__dirname, "tempImageStore.cjs")); },
  get tokenCost() { return require(path.join(__dirname, "tokenCost.cjs")); },
  get tokenUsage() { return require(path.join(__dirname, "tokenUsage.cjs")); },
  get transcriptProbe() { return require(path.join(__dirname, "transcriptProbe.cjs")); },
  get transcriptReader() { return require(path.join(__dirname, "transcriptReader.cjs")); },
  get uiControls() { return require(path.join(__dirname, "uiControls.cjs")); },
  get uiSurfaces() { return require(path.join(__dirname, "uiSurfaces.cjs")); },
  get updateChannel() { return require(path.join(__dirname, "updateChannel.cjs")); },
  get updateCheck() { return require(path.join(__dirname, "updateCheck.cjs")); },
  get videoResearch() { return require(path.join(__dirname, "videoResearch.cjs")); },
  get worktreeService() { return require(path.join(__dirname, "worktreeService.cjs")); },
  get worktreeStore() { return require(path.join(__dirname, "worktreeStore.cjs")); },
  get taskBrainService() { return require(path.join(__dirname, "taskBrainService.cjs")); },
};
