'use strict';

const ttsMute = require('../ttsMute.cjs');
const {
  OPENAI_TRANSCRIBE_URL,
  OPENAI_TTS_URL,
  WHISPER_MODEL,
  SAY_VOICE,
  CLAUDE_TIMEOUT_MS,
  TTS_VOICES,
  DEFAULT_TTS_VOICE,
  DEFAULT_TTS_MODEL,
  TTS_PREVIEW_TEXT,
  DEFAULT_SILENCE_MS,
  MIN_SILENCE_MS,
  MAX_SILENCE_MS,
  DEFAULT_ENDPOINT_MAX_MS,
  DEFAULT_SLEEP_AFTER_MS,
  MIN_SLEEP_AFTER_MS,
  MAX_SLEEP_AFTER_MS,
  normalizeSilenceMs,
  normalizeEndpointMaxMs,
  normalizeSleepAfterMs,
  DEFAULT_NO_SPEECH_MS,
  MIN_NO_SPEECH_MS,
  MAX_NO_SPEECH_MS,
  normalizeNoSpeechMs,
} = require('./constants.cjs');

const {
  parseEnvFile,
  loadEnvLocal,
  openAiKey,
  openAiKeyMissingMessage,
  openAiKeySettingsTarget,
} = require('./envAuth.cjs');

const {
  extForMime,
  resolveExt,
  sttErrorMessage,
  withUserMessage,
  dumpAudioForDebug,
  buildVocabPrompt,
  isHallucinatedSilence,
  transcribeWhisper,
  resolveSttEngine,
  DEFAULT_STT_ENGINE,
  transcribeSpeech,
  whisperLocal,
} = require('./stt.cjs');

const {
  ORCH_SYSTEM,
  BRAIN_TERSE_RULE,
  buildBrainSystemPrompt,
  buildBrainTurnMessage,
  buildBrainPrompt,
  extractJsonObject,
  parseClaudeDecision,
} = require('./brainPrompt.cjs');

const {
  TERMINAL_OPS,
  BROWSER_OPS,
  NAVIGATE_OPS,
  INPUT_OPS,
  BOARD_OPS,
  SPRINT_OPS,
  SETTINGS_OPS,
  MEMORY_OPS,
  REPORT_OPS,
  AGENT_OPS,
  SCREEN_OPS,
  OFFICE_OPS,
  BOARD_STATUSES,
  JARVIS_ACTIONS,
  str,
  reply,
  normalizeInputDecision,
  normalizeBoardDecision,
  normalizeDecision,
  normalizeBrowserDecision,
  normalizeNavigateDecision,
} = require('./decisionNormalize.cjs');

const {
  THEME_BASE_PRESET,
  detectThemeBase,
  detectDepartment,
} = require('./intentPatterns.cjs');

const { parseIntent } = require('./intentParser.cjs');

const {
  applyExecutorPolicy,
  routePromptClass,
} = require('./executorPolicy.cjs');

const {
  claudeBrainSession,
  decideWithClaude,
  brainSession,
  warmupBrain,
  stopBrain,
  brainStats,
  killBrainForTest,
  decideWithSession,
} = require('./brainSession.cjs');

const {
  fastLocalDecision,
  fastPathEnabled,
  decide,
} = require('./decider.cjs');

const {
  SAY_TIMEOUT_MS,
  trackLocalAudioChild,
  untrackLocalAudioChild,
  killLocalAudioChildren,
  liveLocalAudioChildren,
  sweepOrphanSayProcesses,
  speakSay,
  stopPlayback,
} = require('./audioProcess.cjs');

const {
  TTS_CACHE_MAX_CHARS,
  ttsCacheDir,
  ttsCacheFile,
  readTtsCache,
  writeTtsCache,
  speakOpenAI,
  deliverAudioBuffer,
  speakWithSettings,
  speakStreamWithSettings,
  ttsPreview,
  ttsProviders,
  ttsStream,
} = require('./ttsDelivery.cjs');

module.exports = {
  THEME_BASE_PRESET,
  detectThemeBase,
  parseEnvFile,
  loadEnvLocal,
  openAiKey,
  openAiKeyMissingMessage,
  openAiKeySettingsTarget,
  transcribeWhisper,
  transcribeSpeech,
  resolveSttEngine,
  DEFAULT_STT_ENGINE,
  whisperLocal,
  extForMime,
  resolveExt,
  sttErrorMessage,
  withUserMessage,
  isHallucinatedSilence,
  buildVocabPrompt,
  buildBrainPrompt,
  buildBrainSystemPrompt,
  buildBrainTurnMessage,
  BRAIN_TERSE_RULE,
  claudeBrainSession,
  decideWithSession,
  warmupBrain,
  stopBrain,
  brainStats,
  killBrainForTest,
  extractJsonObject,
  parseClaudeDecision,
  normalizeDecision,
  parseIntent,
  fastLocalDecision,
  fastPathEnabled,
  detectDepartment,
  decideWithClaude,
  decide,
  applyExecutorPolicy,
  routePromptClass,
  speakSay,
  SAY_TIMEOUT_MS,
  trackLocalAudioChild,
  untrackLocalAudioChild,
  killLocalAudioChildren,
  liveLocalAudioChildren,
  sweepOrphanSayProcesses,
  speakOpenAI,
  readTtsCache,
  writeTtsCache,
  ttsCacheFile,
  TTS_CACHE_MAX_CHARS,
  speakWithSettings,
  speakStreamWithSettings,
  ttsStream,
  stopPlayback,
  ttsProviders,
  deliverAudioBuffer,
  ttsPreview,
  ttsMute,
  TTS_PREVIEW_TEXT_TR: ttsProviders.TTS_PREVIEW_TEXT_TR,
  SAY_VOICE,
  WHISPER_MODEL,
  TTS_VOICES,
  TTS_PREVIEW_TEXT,
  DEFAULT_TTS_VOICE,
  DEFAULT_TTS_MODEL,
  DEFAULT_SILENCE_MS,
  MIN_SILENCE_MS,
  MAX_SILENCE_MS,
  normalizeSilenceMs,
  normalizeEndpointMaxMs,
  normalizeSleepAfterMs,
  normalizeNoSpeechMs,
  DEFAULT_NO_SPEECH_MS,
  MIN_NO_SPEECH_MS,
  MAX_NO_SPEECH_MS,
  DEFAULT_ENDPOINT_MAX_MS,
  DEFAULT_SLEEP_AFTER_MS,
};
