'use strict';

const { tagTestWindow, E2E_WINDOW_TAG } = require('./tagTestWindow');
const { createSharedWebPreferences } = require('./sharedPreferences');
const { attachHtmlFullscreenGuard } = require('./htmlFullscreenGuard');
const { applyGuestPermissionPolicy, attachWebviewGuards } = require('./webviewGuards');
const { createAppWindow } = require('./mainWindow');
const { createSpikeWindow } = require('./spikeWindow');
const {
  popoutWindows,
  popoutWindowFor,
  popoutPaneIdForWindow,
  sendPaneEvent,
  notifyPopoutState,
  openPopoutWindow,
  closePopoutWindow,
  listPopoutPanes,
  broadcastPaneView,
  broadcastPaneDraft,
  broadcastClipChanged,
} = require('./popoutWindow');
const {
  DESIGN_WINDOW_KEY,
  DESIGN_WINDOW_MIN,
  designWindowAlive,
  getDesignWindow,
  setDesignWindow,
  notifyDesignWindowOpen,
  openDesignWindow,
  closeDesignWindow,
} = require('./designWindow');
const {
  JARVIS_WIDGET_KEY,
  jarvisWidgetAlive,
  getJarvisWidgetWindow,
  setJarvisWidgetWindow,
  getJarvisWidgetSnapshot,
  setJarvisWidgetSnapshot,
  jarvisWidgetPayload,
  broadcastJarvisWidget,
  notifyJarvisWidgetOpen,
  jarvisWidgetWorkArea,
  openJarvisWidgetWindow,
  closeJarvisWidgetWindow,
  moveJarvisWidget,
} = require('./jarvisWidgetWindow');
const {
  handOverlayWindows,
  handTuningConfig,
  handOverlayPrefs,
  handOverlayAnyAlive,
  getHandOverlayLastCost,
  setHandOverlayLastCost,
  getHandOverlayLastFeedAt,
  getHandOverlayDebugInfo,
  openHandOverlayWindows,
  closeHandOverlayWindows,
  rebuildHandOverlayWindows,
  hookHandOverlayScreenEvents,
  startHandOverlayWatchdog,
  stopHandOverlayWatchdog,
  feedHandOverlay,
  applyHandOverlaySettings,
} = require('./handOverlayWindows');
const {
  handDetectAlive,
  openHandDetectWindow,
  scheduleHandControlWarmup,
} = require('./handDetectWindow');

function createWindowManager(deps) {
  const sharedWebPreferences = () => createSharedWebPreferences(deps);
  const enrichedDeps = { ...deps, sharedWebPreferences };

  return {
    sharedWebPreferences,
    tagTestWindow: (win, base) => tagTestWindow(win, base, deps.isTest),
    attachHtmlFullscreenGuard: (win, wc) => attachHtmlFullscreenGuard(win, wc, deps.logLine),
    applyGuestPermissionPolicy: (ses) => applyGuestPermissionPolicy(ses, enrichedDeps),
    attachWebviewGuards: (win) => attachWebviewGuards(win, enrichedDeps),
    createAppWindow: (url) => createAppWindow(url, enrichedDeps),
    createSpikeWindow: () => createSpikeWindow(enrichedDeps),
    popoutWindows,
    popoutWindowFor,
    popoutPaneIdForWindow,
    sendPaneEvent,
    notifyPopoutState: (channel, payload) => notifyPopoutState(channel, payload, enrichedDeps),
    openPopoutWindow: (options) => openPopoutWindow(options, enrichedDeps),
    closePopoutWindow,
    listPopoutPanes,
    broadcastPaneView: (paneId, readable) => broadcastPaneView(paneId, readable, enrichedDeps),
    broadcastPaneDraft: (paneId, text) => broadcastPaneDraft(paneId, text, enrichedDeps),
    broadcastClipChanged: () => broadcastClipChanged(enrichedDeps),
    DESIGN_WINDOW_KEY,
    DESIGN_WINDOW_MIN,
    designWindowAlive,
    getDesignWindow,
    setDesignWindow,
    notifyDesignWindowOpen: () => notifyDesignWindowOpen(enrichedDeps),
    openDesignWindow: () => openDesignWindow(enrichedDeps),
    closeDesignWindow,
    JARVIS_WIDGET_KEY,
    jarvisWidgetAlive,
    getJarvisWidgetWindow,
    setJarvisWidgetWindow,
    getJarvisWidgetSnapshot,
    setJarvisWidgetSnapshot,
    jarvisWidgetPayload: () => jarvisWidgetPayload(enrichedDeps),
    broadcastJarvisWidget: () => broadcastJarvisWidget(enrichedDeps),
    notifyJarvisWidgetOpen: () => notifyJarvisWidgetOpen(enrichedDeps),
    jarvisWidgetWorkArea,
    openJarvisWidgetWindow: () => openJarvisWidgetWindow(enrichedDeps),
    closeJarvisWidgetWindow,
    moveJarvisWidget,
    handOverlayWindows,
    handTuningConfig,
    handOverlayPrefs,
    handOverlayAnyAlive,
    getHandOverlayLastCost,
    setHandOverlayLastCost,
    getHandOverlayLastFeedAt,
    getHandOverlayDebugInfo,
    openHandOverlayWindows: () => openHandOverlayWindows(enrichedDeps),
    closeHandOverlayWindows: (reason) => closeHandOverlayWindows(reason, deps.logLine),
    rebuildHandOverlayWindows: () => rebuildHandOverlayWindows(enrichedDeps),
    hookHandOverlayScreenEvents: () => hookHandOverlayScreenEvents(enrichedDeps),
    startHandOverlayWatchdog,
    stopHandOverlayWatchdog,
    feedHandOverlay: (rawEvents) => feedHandOverlay(rawEvents, enrichedDeps),
    applyHandOverlaySettings,
    handDetectAlive: () => handDetectAlive(enrichedDeps),
    openHandDetectWindow: () => openHandDetectWindow(enrichedDeps),
    scheduleHandControlWarmup: (attempt) => scheduleHandControlWarmup(attempt, enrichedDeps),
  };
}

module.exports = {
  createWindowManager,
  tagTestWindow,
  E2E_WINDOW_TAG,
  createSharedWebPreferences,
  attachHtmlFullscreenGuard,
  applyGuestPermissionPolicy,
  attachWebviewGuards,
  createAppWindow,
  createSpikeWindow,
  popoutWindows,
  popoutWindowFor,
  popoutPaneIdForWindow,
  sendPaneEvent,
  notifyPopoutState,
  openPopoutWindow,
  closePopoutWindow,
  listPopoutPanes,
  broadcastPaneView,
  broadcastPaneDraft,
  broadcastClipChanged,
  DESIGN_WINDOW_KEY,
  DESIGN_WINDOW_MIN,
  designWindowAlive,
  getDesignWindow,
  setDesignWindow,
  notifyDesignWindowOpen,
  openDesignWindow,
  closeDesignWindow,
  JARVIS_WIDGET_KEY,
  jarvisWidgetAlive,
  getJarvisWidgetWindow,
  setJarvisWidgetWindow,
  getJarvisWidgetSnapshot,
  setJarvisWidgetSnapshot,
  jarvisWidgetPayload,
  broadcastJarvisWidget,
  notifyJarvisWidgetOpen,
  jarvisWidgetWorkArea,
  openJarvisWidgetWindow,
  closeJarvisWidgetWindow,
  moveJarvisWidget,
  handOverlayWindows,
  handTuningConfig,
  handOverlayPrefs,
  handOverlayAnyAlive,
  getHandOverlayLastCost,
  setHandOverlayLastCost,
  getHandOverlayLastFeedAt,
  getHandOverlayDebugInfo,
  openHandOverlayWindows,
  closeHandOverlayWindows,
  rebuildHandOverlayWindows,
  hookHandOverlayScreenEvents,
  startHandOverlayWatchdog,
  stopHandOverlayWatchdog,
  feedHandOverlay,
  applyHandOverlaySettings,
  handDetectAlive,
  openHandDetectWindow,
  scheduleHandControlWarmup,
};
