'use strict';

module.exports = Object.freeze({
    id: 'jev',
    label: 'Jev AI (Orchestrator)',
    bin: 'jev',
    defaultArgs: Object.freeze([]),
    autonomy: Object.freeze({
      level: 'full',
      via: null,
      flags: Object.freeze([]),
      measured: 'Jev AI Akıllı Model Yönlendirici: Görevleri analiz ederek bağlı motorlar arasından en uygun AI modelini seçer',
      why: 'Maliyet tasarrufu, token optimizasyonu ve hız artışı sağlar'
    }),
    identity: null,
    model: Object.freeze({
      flag: '--model',
      default: 'auto',
      supported: Object.freeze(['auto', 'fast', 'smart', 'expert'])
    }),
    effort: null,
    images: null,
    provider: null,
    session: null,
    contextScope: null,
    subagentBlock: null,
    trust: null,
    reset: null,
    tui: null,
    mcp: null,
    hooks: null,
    extraRoots: null,
    skillsDir: null,
    identityEnv: null,
    auth: Object.freeze({
      label: 'Jev AI',
      accountHint: 'Jev AI Akıllı Model Yönlendirici — bağlı AI motorları arasından göreve göre en uygun modeli belirler',
      signupUrl: 'https://jev.ai/',
      flow: 'api-key',
      needsCode: false,
      loginArgv: null,
      logoutArgv: null,
      statusArgv: null,
      statusParse: null,
      statusNote: 'Jev AI akıllı model yönlendirme motoru olarak yapılandırılmıştır.',
      apiKey: Object.freeze({
        env: 'JEV_API_KEY',
        vaultService: 'jev',
        keyUrl: 'https://jev.ai/api-keys',
        keyLabel: 'Jev AI API anahtarı'
      })
    }),
    usage: null,
    output: null,
    install: null,
    unsupported: Object.freeze({
      identity: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      effort: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      images: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      provider: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      session: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      subagentBlock: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      contextScope: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      trust: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      reset: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      tui: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      mcp: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      hooks: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      extraRoots: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      skillsDir: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      identityEnv: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      usage: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      output: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.',
      install: 'Jev AI bir model yönlendirici (orchestrator) motorudur; doğrudan pane çalıştırmaz, bağlı motorları yönlendirir.'
    }),
    partial: Object.freeze({}),
    verification: Object.freeze({
      identity: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      model: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      effort: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      images: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      provider: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      session: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      subagentBlock: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      contextScope: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      trust: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      reset: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      tui: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      mcp: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      hooks: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      extraRoots: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      skillsDir: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      identityEnv: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      auth: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      usage: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      output: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' },
      install: { channel: 'source', source: 'Jev AI Akıllı Model Yönlendirici spesifikasyonu' }
    })
});
